name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  GITHUB_TOKEN: ${{secrets.TEST_USER_TOKEN}}
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        cd 2021/dotnet
        dotnet restore
    - name: Build
      run: |
        cd 2021/dotnet
        dotnet build --no-restore
    - name: Test
      run: |
        cd 2021/dotnet
        dotnet test --no-build --verbosity normal
