name: Java

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Lint
        working-directory: ./java/github-tests
        run: |
          ./gradlew clean checkstyleMain
          ./gradlew clean checkstyleTest

      - name: Run Tests
        working-directory: ./java/github-tests
        env:
          GITHUB_USER: ${{ secrets.TEST_GITHUB_USER }}
          GITHUB_REPO: ${{ secrets.TEST_GITHUB_REPO }}
          GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
        run: ./gradlew clean test
