name: NodeJS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  GITHUB_TOKEN: ${{secrets.TEST_USER_TOKEN}}
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        cd 2021/typescript
        npm ci
    - name: Run API Tests
      run: |
        cd 2021/typescript
        npm run test:api
    - name: Run UI Tests
      run: |
        cd 2021/typescript
        npm run test:web
